# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import migrations, models
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eve_sso', '0002_scopes_20160501_2301'),
    ]

    operations = [
        # Rename owner and add related_name to user model
        migrations.RenameField(
            model_name='accesstoken',
            old_name='user',
            new_name='owner',
        ),
        migrations.AlterField(
            model_name='accesstoken',
            name='owner',
            field=models.ForeignKey(related_name='tokens', to=settings.AUTH_USER_MODEL, help_text='The user to whom this token belongs.', null=True),
        ),
        # Add index
        migrations.AlterField(
            model_name='accesstoken',
            name='character_id',
            field=models.IntegerField(help_text='The ID of the EVE character who authenticated by SSO.', db_index=True),
        ),
        # Just change help texts
        migrations.AlterField(
            model_name='accesstoken',
            name='created',
            field=models.DateTimeField(help_text='Datetime when this token was created', auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='accesstoken',
            name='scopes',
            field=models.ManyToManyField(help_text='The access scopes granted by this SSO token.', related_name='tokens', to='eve_sso.Scope'),
        ),
        migrations.AlterField(
            model_name='accesstoken',
            name='token_type',
            field=models.CharField(default='Character', help_text='The applicable range of the token.', max_length=16, choices=[('Character', 'Character'), ('Corporation', 'Corporation')]),
        ),
        migrations.AlterField(
            model_name='callbackredirect',
            name='hash_string',
            field=models.CharField(help_text='Cryptographic hash used to reference this callback.', unique=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='callbackredirect',
            name='session_key',
            field=models.CharField(help_text='Session key identifying session this redirect was created for.', max_length=254),
        ),
        migrations.AlterField(
            model_name='callbackredirect',
            name='token',
            field=models.ForeignKey(related_name='callbacks', to='eve_sso.AccessToken', help_text='AccessToken generated by a completed code exchange from callback processing.', null=True),
        ),
    ]
